### ISSUE TITLE
Instrucciones para usar github.io como CDN

### ISSUE THREAD

**Issue by IvanSanchez** [sigdeletras/Leaflet.Spain.WMS#1]
Cambiar el README para que las instrucciones incluyan una referencia a https://sigdeletras.github.io/Leaflet.Spain.WMS/src/Leaflet.Spain.WMS.js, p. ej.:

``` HTML
<script src='https://sigdeletras.github.io/Leaflet.Spain.WMS/src/Leaflet.Spain.WMS.js'></script>
```

Esto no quita que se incluyan instrucciones para clonar el repo, pero supongo que habrá usuarios que no quieran aprender git para usar el plugin.

**Comment by sigdeletras** [comment]
Listo. He creado la rama gh-pages y actualizado esa parte en el README. Marrón 1 Listo..jejeje

**Comment by IvanSanchez** [comment]
Nota: Es una buena práctica el hacer referencia a los tickets en los comentarios del commit. Por ejemplo, en vez de "update README", "update README, fixes #1". Además esto cierra los tickets automáticamente. :-)

**Comment by sigdeletras** [comment]
Creo que hasta que uno no se mete en serio en esto no aprende de verdad. Creo que el marrón lo vas a tener tú mas conmigo que yo contigo...jejeje
