### ISSUE TITLE
Ejemplos en vivo

### ISSUE THREAD

**Issue by IvanSanchez** [sigdeletras/Leaflet.Spain.WMS#2]
Añadir una página de ejemplo en la rama `gh-pages`, que sea visitable por cualquier usuario.

Véase como ejemplo https://github.com/IvanSanchez/Leaflet.MandelbrotGL/blob/gh-pages/demo.html versus https://ivansanchez.github.io/Leaflet.MandelbrotGL/demo.html

**Comment by sigdeletras** [comment]
Ok. [http://sigdeletras.github.io/Leaflet.Spain.WMS/examples/](http://sigdeletras.github.io/Leaflet.Spain.WMS/examples/)
