### ISSUE TITLE
Altura punto

### ISSUE THREAD

**Issue by tom-vb** [sigdeletras/Leaflet.Spain.WMS#6]
Hola,
hay alguna manera de optener la altura de un punto?

**Comment by sigdeletras** [comment]
Hola @tom-vb 
El complemento está pensado solo para cargar servicios  WMS. No tienen la peticón gefeaturetinfo pensada para devolver datos.

Además para este tipo de consultas se usan servicios WCS, en este caso con alturas. El complemento no realiza por lo tanto esa funcionalidad.

Un saludo
